### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#1]
Connections can fail, more better logging would be helpful

**Comment by anushkrishnav** [comment]
I would love to work on this with some guidance

**Comment by anushkrishnav** [comment]
Where do I start ?

**Comment by 4n4nd** [comment]
> Where do I start ?

Maybe look for places where you could add more debug statements? ([like these](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/prometheus_connect.py#L192-L194))
