### ISSUE TITLE
Why is this repo deleted?

### ISSUE THREAD

**Issue by melrom** [AICoE/prometheus-api-client-python#1]
Hello, can anyone please explain why the code was deleted from this repo? Thanks... @4n4nd ....

**Comment by JamesTessmer** [comment]
I'm not part of this project, but ran into this deleted repo while looking for the code as well. It looks like it has been moved to @4n4nd 's github.
https://github.com/4n4nd/prometheus-api-client-python

**Comment by 4n4nd** [comment]
hey folks, we moved this repo from the AICoE org to https://github.com/4n4nd/prometheus-api-client-python because of some internal org changes. Please create any new issues/PRs in the new repo location. Thanks!

**Comment by jinnatar** [comment]
You may want to update PyPi as it still links to this repo.

**Comment by samclam23** [comment]
Yes pypi still directs here

**Comment by 4n4nd** [comment]
Made a PR: https://github.com/4n4nd/prometheus-api-client-python/pull/248
