### ISSUE TITLE
prometheus_connect.py ---PrometheusConnect---HTTPS ACCESS

### ISSUE THREAD

**Issue by frankcgq105** [AICoE/prometheus-api-client-python#103]
how to access HTTPS?
it seems there is no the CERT argu to send  the API PrometheusConnect
when I use disable_ssl: False,then the PrometheusConnect function's argu ssl_verification will be turn to  true.

Then it should access the HTTPS by cert file,but how to transfer CERT into the API?

Thanks a lot.

**Comment by 4n4nd** [comment]
that is a very good question, this needs to be changed. I'll assign myself to this. 

Until then, can you manually change the [ssl_verification](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/prometheus_connect.py#L45) variable for your PrometheusConnect Object to point it to the certs?

it should be similar to this:
```python
my_pc = PrometheusConnect()
my_pc.ssl_verification = "path/to/certs"
```

Thanks for letting us know :+1:

**Comment by frankcgq105** [comment]
OK,thanks a lot, I'll try it and give the reponse
