### ISSUE TITLE
Add getting started content to README.md

### ISSUE THREAD

**Issue by durandom** [AICoE/prometheus-api-client-python#119]
How about adding some small code snippets that highlight the features of the library and how it's used.
Just like in https://github.com/prometheus/prometheus_api_client_ruby

**Comment by hemajv** [comment]
I think we had some content while building the katacoda scenarios, can refine that and also this would be beneficial for our upcoming devconf workshop as well

**Comment by hemajv** [comment]
apologies for the delay, will ensure to submit a PR today
