### ISSUE TITLE
Fedora RPM

### ISSUE THREAD

**Issue by dankenigsberg** [AICoE/prometheus-api-client-python#121]
I'm an old-fashioned guy who likes to consume his code via `dnf install foo`, where it is generally less random and better controlled by an organization that I already trust. Would you contribute this code to Fedora as a `python3-prometheus-api-client.rpm` ?

**Comment by durandom** [comment]
@goern didnt you do something similar with a Thoth component? Do you have these steps documented or have somebody to assist?
