### ISSUE TITLE
readthedocs landing page is rather empty

### ISSUE THREAD

**Issue by dankenigsberg** [AICoE/prometheus-api-client-python#125]
**Describe the bug**
https://prometheus-api-client-python.readthedocs.io/en/latest/index.html is quite empty. It should have a word about what the library does, how to obtain it, and (links to?) basic usage.

**Comment by 4n4nd** [comment]
this isn't really a bug, we just didn't get the chance to add some basic usage info.
Should be related to https://github.com/AICoE/prometheus-api-client-python/issues/119

**Comment by 4n4nd** [comment]
i'll create a project card for this, so we can track this
