### ISSUE TITLE
Pandas range dataframe

### ISSUE THREAD

**Issue by allenmqcymp** [AICoE/prometheus-api-client-python#130]
**Problem**
I would like to be able to get a Pandas Dataframe of a PromQL range query, instead of just having the instantaneous dataframe, which comprises the first or last values of a range query at the moment.

**Proposal**
A new class called `MetricRangeDataFrame` which creates a Pandas MultiIndex. The DataFrame could look something like this, where timestamp is its own index and all the other labels and __name__ fields are the same as in `MetricSnapshotDataFrame`

**Example**
![multi2](https://user-images.githubusercontent.com/16281832/88431468-66cbb180-cdc8-11ea-93c0-9b04d65ae9aa.png)

**Alternatives**
Extending the current MetricRangeDataFrame is a possible solution, however, I'm thinking its better to make two independent dataframe types corresponding to an instant vector and a range vector in PromQL.

**Comments**
If this is a viable option, I can work on adding this.

Best,
Allen

**Comment by chauhankaranraj** [comment]
I like this idea. @4n4nd, correct me if I'm wrong, but IIRC we had talked about doing something like this when we were planning `MetricSnapshotDataFrame`, but we never got around to it for some reason. I think this can be a useful feature. wdyt?

**Comment by 4n4nd** [comment]
> we had talked about doing something like this when we were planning `MetricSnapshotDataFrame`

yeah I think it was supposed to be a "range" version of the `MetricSnapshotDataFrame`

> I think this can be a useful feature

Agreed :100: 
@allenmqcymp if you can work on adding this, I think it would be a great addition :+1:
