### ISSUE TITLE
`examples/MetricsList_example.ipynb` is broken due to inaccessible server

### ISSUE THREAD

**Issue by martinpovolny** [AICoE/prometheus-api-client-python#145]
**Describe the bug**

`examples/MetricsList_example.ipynb` does not work. The server does not exist (even inside the VPN).

**To Reproduce**
Open the notebook via `jupyter notebook examples/MetricsList_example.ipynb`

Observe a number of cells fail.

**Expected behavior**
Cells would render fine.

**Additional context**

If we implement result caching (https://github.com/AICoE/prometheus-api-client-python/issues/82) then the notebook example might include the cached requests and would work w/o access to the server.

**Comment by 4n4nd** [comment]
oh that's because the metrics we are using in the notebook are not available anymore :(

**Comment by 4n4nd** [comment]
I can replace the internal Prometheus instance to http://demo.robustperception.io:9090/graph
also we need to update the prometheus-api-client version in the notebook.
