### ISSUE TITLE
New version on pypi

### ISSUE THREAD

**Issue by rsevilla87** [AICoE/prometheus-api-client-python#149]
Hi, my team and I are using some features (bfb6eee8040ccd5b53c0bb09e26b98b89cfc542c) of this library that are not available in the published package in PyPI. When do you have plans to publish a new version?

Thanks!

**Comment by 4n4nd** [comment]
#150 Should have released a new version `0.4.1`

**Comment by rsevilla87** [comment]
Oh, thats great. Thank you very much :)
