### ISSUE TITLE
[Operate First] Create a blog post about basic interaction with Prometheus Metrics using the API

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#164]
Could be basic metrics stuff or 
We could also add something more data sciency with the metrics

**Comment by anushkrishnav** [comment]
With some guidance, I would love to work on this

**Comment by goern** [comment]
Cc: @durandom

**Comment by 4n4nd** [comment]
@Shreyanand

**Comment by Shreyanand** [comment]
Tracked a similar issue in the time series analysis repository. Check this [pull request](https://github.com/aicoe-aiops/time-series/pull/4). 
The time series analysis [repository](https://github.com/aicoe-aiops/time-series) is a collection of notebooks (and corresponding blog posts) to be published on operate first.

**Comment by 4n4nd** [comment]
@Shreyanand can we close this issue?

**Comment by Shreyanand** [comment]
Yup! Here's the [post](https://www.operate-first.cloud/data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb).
