### ISSUE TITLE
Create an instructional notebook image for the Obslytics tool

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#179]
Build the obslytics binary and use it in jupyterhub images so that DS can directly import data directly from thanos or even prometheus

**Comment by chauhankaranraj** [comment]
I'm happy work on the exploratory notebook for this :)

**Comment by 4n4nd** [comment]
Thanks!

**Comment by anushkrishnav** [comment]
I wish to take up the Issue

**Comment by 4n4nd** [comment]
@anushkrishnav I think @chauhankaranraj might have already started working on this issue

**Comment by chauhankaranraj** [comment]
> @anushkrishnav I think @chauhankaranraj might have already started working on this issue

Yeah I did start working on this but couldn't work on it this last sprint. I'm planning on finishing it next sprint, but if not then I'll let you folks know on here :)

**Comment by chauhankaranraj** [comment]
It looks like Obslytics already stores data in a data analysis friendly data format, it just has to be downloaded (`s3.download_fileobj()`) and read (`pd.read_parquet`). So imho the main "instructional" part of this notebook would be how to set up and run the Obslytics tool, which admittedly I as a data scientist don't have expertise in.

@4n4nd how would you feel about adding that bit first, and once that is in, then maybe I can work on showing how to load it and do some basic analysis?

**Comment by 4n4nd** [comment]
yeah I can do that :+1:
