### ISSUE TITLE
Introduce check connection method for Prometheus

### ISSUE THREAD

**Issue by pacospace** [AICoE/prometheus-api-client-python#180]
**Is your feature request related to a problem? Please describe.**<br>
As user of Prometheus API client,

I would like to have a way to check if the endpoint is available or my inputs are correct for connection before trying to fetch many types of metrics and immediately stop the application.

**Describe the solution you'd like**<br>
Introduce a method that returns True/False if the endpoint is available or not.

**Describe alternatives you've considered**<br>

**Additional context**<br>

**Comment by pacospace** [comment]
@4n4nd how do you plan to release here? and do you use Bot to release?

**Comment by 4n4nd** [comment]
@pacospace oh yes we do use the bot to release, let me create a new one :+1:

**Comment by pacospace** [comment]
> @pacospace oh yes we do use the bot to release, let me create a new one

Thanks you very much @4n4nd :rocket:
