### ISSUE TITLE
Missing timestamp validity checks in  get_metric_range_data

### ISSUE THREAD

**Issue by chauhankaranraj** [AICoE/prometheus-api-client-python#191]
**Describe the bug**
If a user accidentally passes an [end_time](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/prometheus_connect.py#L162) that is before [start_time](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/prometheus_connect.py#L161) ( like I did :) ), then the `get_metric_range_data` function returns an empty list instead of throwing an error.

**To Reproduce**
1. Instantiate `PrometheusConnect` object
2. Using this object call the `get_metric_range_data` func with end_time < start_time
3. See empty list

**Expected behavior**
If the user were to make this timestamp switcharoo while using the `custom_query_range` function, then the HTTP code 400 would returned with the message `end timestamp must not be before start time`. So maybe something similar should happen for `get_metric_range_data` as well?

**Screenshots**
![Screenshot from 2021-01-27 12-24-10](https://user-images.githubusercontent.com/15005500/106029027-ab4b4900-609a-11eb-9419-f648a984209d.png)

**Comment by anushkrishnav** [comment]
I am intrested

**Comment by 4n4nd** [comment]
/assign @anushkrishnav 
Thanks!

**Comment by anushkrishnav** [comment]
Will send in a PR soon @4n4nd 
Is there any slack group or a similar place ? i would love to join and get more involved I am in my pre final year and would learn a lot from the team

**Comment by 4n4nd** [comment]
Hey @anushkrishnav, yes we do have a gchat and a slack channel. The links should be available in this issue: https://github.com/AICoE/prometheus-api-client-python/issues/188
Please lmk if they don't work.

**Comment by anushkrishnav** [comment]
@4n4nd the slack invite is no longer available

**Comment by 4n4nd** [comment]
@anushkrishnav I think you can join the Operate-First Group on Slack using this [link](https://join.slack.com/t/operatefirst/shared_invite/zt-o2gn4wn8-O39g7sthTAuPCvaCNRnLww) this link will expire in 30 days or so.
There you can find a channel I just created `help-prometheus-api-client-python`. Lmk if there are any issues.
