### ISSUE TITLE
Usage Question - custom_query vs get_metric_range_data

### ISSUE THREAD

**Issue by Shackelford-Arden** [AICoE/prometheus-api-client-python#197]
**Question**

I have the following custom query:

```
rate(memcached_evictions{environment=~'production',location=~'location1',service='service1'}[1m])
```

When I get the data return over raw HTTP (w/ requests.get()) I get my results back as a `vector` resultType with other related metric data. The values returned are what I expected:

"value": [<float>, "0"]

Using `custom_query` I can obtain the same results. But when I attempt to use one of the other methods you kind folks provide, such as get_metric_range_data, the results returned are quite different than what I'd expect. What am I missing?

Here's the code I'm using for `get_metric_data_range`:

```python

start_time = parse_datetime("15m")
end_time = parse_datetime("now")

curr_range_data = prom.get_metric_range_data(
    metric_name="memcached_evictions{environment=~'production',location=~'location1',service='service1'}",
    start_time=start_time,
    end_time=end_time
)

calc_range_data = MetricSnapshotDataFrame(curr_range_data)
```

The data returned when printing out `calc_range_data`:

```
__name__                value
memcached_evictions ... 3452222
memcached_evictions ... 3333263
memcached_evictions ... 13454715
memcached_evictions ... 9638913
```

Based on the results I get back from `custom_query` and the Prometheus Expression Browser, the values returned here are quite different from the expected values.

Now, I feel like I'm doing something wrong here in how I'm using these pieces, I don't believe this to be a bug in the code. Just trying to understand how to best make use of ya'lls good work :)

Any guidance here is greatly appreciated.

**Comment by 4n4nd** [comment]
@Shackelford-Arden are you saying the `curr_range_data` and `calc_range_data` have different values or that the `curr_range_data` has different values compared to what you see in the prometheus console?
Basically, I am trying to understand whether the data queried from Prometheus is different or the data when converted to a dataframe is different.

**Comment by Shackelford-Arden** [comment]
Sorry, I could have made that more clear :) 

`curr_range_data` and `calc_range_data` is the same after the conversion.

The difference is the data I see when compared to the Prometheus console.

Now, I am not 100% that I'm using this correctly. Right, my "raw" query includes a `rate()` call, which I believe is getting me the value of 0 that I expect/need. If I wanted to use `rate()`, am I going to always have to use `custom_query`?

**Comment by 4n4nd** [comment]
So, could you try collecting more data (say 1 day worth of data) and plot it? Both in console and in python? Can you check if there is a shift in the plot?

The only thing that can make it different is the start and end times. 
Maybe your Prometheus host and python host are in different timezones?

Thanks!
