### ISSUE TITLE
Treat unique label configs as separate time series in MetricRangeDataFrame

### ISSUE THREAD

**Issue by chauhankaranraj** [AICoE/prometheus-api-client-python#198]
**Is your feature request related to a problem? Please describe.**<br>
[MetricRangeDataFrame](https://github.com/AICoE/prometheus-api-client-python/blob/2f4cba0602be97637caf66790a50076b79d1704f/prometheus_api_client/metric_range_df.py) formats results of data type ["range vector"](https://prometheus.io/docs/prometheus/latest/querying/basics/#expression-language-data-types) into an easy to work with pandas dataframe. However, in this representation the time series are not "collated" or "grouped" by unique label combinations. i.e., the dataframe looks something like this:

![Screenshot from 2021-04-12 17-33-54](https://user-images.githubusercontent.com/15005500/114465607-573e0400-9bb5-11eb-8535-6f13c9a55209.png)

So in order to analyze, inspect, or plot the time series corresponding to each unique label configuration, I first have to do the additional step of grouping the dataframe by labels.

**Describe the solution you'd like**<br>
A dataframe where the unique label combinations are set as the [MultiIndex](https://pandas.pydata.org/docs/user_guide/advanced.html) for the dataframe, and the values are the time series values. i.e., a dataframe that looks something like this:

![Screenshot from 2021-04-12 17-34-14](https://user-images.githubusercontent.com/15005500/114466523-991b7a00-9bb6-11eb-9106-f7da326dae29.png)

**Describe alternatives you've considered**<br>
- Manually calling the [`set_index`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) function with the relevant label names
- Manually doing a [`groupby`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) with the relevant label names

**Additional context**<br>
This would also be more consistent with what thanos output looks like
![Screenshot from 2021-04-12 17-46-44](https://user-images.githubusercontent.com/15005500/114466977-2bbc1900-9bb7-11eb-969f-538cec7eb2bf.png)

**Comment by chauhankaranraj** [comment]
@4n4nd Do you think this would be a valuable addition? Or is this **not** how you'd imagine the users would generally use it?

/cc @MichaelClifford @Shreyanand

**Comment by 4n4nd** [comment]
I am all for making it more consistent with the Prometheus console output :+1:

**Comment by MichaelClifford** [comment]
:+1: @chauhankaranraj 

I'm all for this change to provide the time series grouped by unique labels as the default behavior. That said, we could use multi-indexing and maintain everything in a single DF, or we could divided the collected data into a dictionary that has a DF for each unique label set. Which may make it easier for someone to understand the data and work with the entities they are interested in. But just an alternate suggestion to consider : )

**Comment by chauhankaranraj** [comment]
> we could divided the collected data into a dictionary that has a DF for each unique label set. Which may make it easier for someone to understand the data and work with the entities they are interested in. But just an alternate suggestion to consider : )

Oh yeah, I think if having a separate df for each label config is more suited to the use case, then maybe just `MetricsList` could be used? I think it does precisely that (following snippet put together from the [example notebook](https://github.com/AICoE/prometheus-api-client-python/blob/559434db91bd59af7adadc41456a3f889f09ddb6/examples/MetricsList_example.ipynb)). wdyt?

![Screenshot from 2021-04-27 14-34-58](https://user-images.githubusercontent.com/15005500/116294740-53d67b00-a766-11eb-9062-e2cd936394dd.png)

**Comment by Lobo-m4** [comment]
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html
