### ISSUE TITLE
"step" in get_metric_range_data method

### ISSUE THREAD

**Issue by Shreyanand** [AICoE/prometheus-api-client-python#204]
**Is your feature request related to a problem? Please describe.**<br>
As a user, I would like to get aggregated data using the "get_metric_range_data" method. The default resolution of data is in seconds. If I want data for a year, the number of data points is huge and it takes a lot of compute resources to download and store the data. I would like to get the data in hourly or daily frequency. For that, there needs to be an aggregator in the get_metric_range_data method. 

**Describe alternatives you've considered**<br>
I tried using "avg_over_time(metric[1h])" for the metric_name parameter but it didn't work and it seems like a hack.

**Comment by 4n4nd** [comment]
`step` seems like a good parameter to add to range queries, this would make the api client more "complete" with the api ([api docs](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries)).

I think we can add `step` and also the `timeout` parameter while we are at it

**Comment by 4n4nd** [comment]
Just checked, we are using the `query` API and not the `query_range` API for the `get_metric_range_data` function (not sure if this is the best way to do it, I'll have to look into it). 
But you can use the [`custom_query_range` function](https://prometheus-api-client-python.readthedocs.io/en/master/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.custom_query_range) which has the `step` parameter set up.
