### ISSUE TITLE
MetricSnapshotDataFrame Excepts When Passed an Empty List

### ISSUE THREAD

**Issue by Shackelford-Arden** [AICoE/prometheus-api-client-python#207]
**Describe the bug**

Not sure that I want to truly declare this a bug, but felt this was maybe a good place to start?

When running a query against Prometheus and no results are returned, we're given an empty list.

For example:

```python
    metric_data = prom.get_current_metric_value(metric_name='<my_metric>')
    metric_df = MetricSnapshotDataFrame(metric_data)
```

The example for this project (which is mimicked above) likely assumes that this will _always_ return data (ie not an empty list). However, as I've learned, I can pass in a query to `get_current_metric_value`'s `metric_name` and I can still get accurate data, and passing in a query may lead to being given back an empty list.

If I pass the empty list into the `MetricSnapshotDataFrame` (again following the examples here), we run into a fun little scenario with Pandas exceptions. I believe the exception itself is happening [around here](https://github.com/AICoE/prometheus-api-client-python/blob/559434db91bd59af7adadc41456a3f889f09ddb6/prometheus_api_client/metric_snapshot_df.py#L83).

**Expected behavior**

I'm wondering if, at a minimum, the logic might be placed within `MetricSnapshotDataFrame` to raise a specific exception that the list passed in is empty. 

Maybe [this line](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/metric_snapshot_df.py#L62) could be something like:

```python
    if not isinstance(data, Sequence) and data:
```

This would catch the empty list and avoid excepting out due to Pandas being unhappy ;).

**Comment by Shackelford-Arden** [comment]
Oh, and I'll note that, yes, on my end I should be checking (and now am) that the `metric_data` actually contains data. However, I still felt like it'd be good to add something useful to others who may have forgotten to check.

**Comment by chauhankaranraj** [comment]
@Shackelford-Arden Thanks for opening an issue for this! Could you please provide some more details on how to replicate this error?

> If I pass the empty list into the `MetricSnapshotDataFrame` (again following the examples here), we run into a fun little scenario with Pandas exceptions. I believe the exception itself is happening [around here](https://github.com/AICoE/prometheus-api-client-python/blob/559434db91bd59af7adadc41456a3f889f09ddb6/prometheus_api_client/metric_snapshot_df.py#L83).

I tried to do the following but it doesn't seem to exception out for me.

![Screenshot from 2021-06-17 16-29-50](https://user-images.githubusercontent.com/15005500/122468123-4af56f00-cf89-11eb-960c-22b4f3d0413a.png)

**Comment by Shackelford-Arden** [comment]
@chauhankaranraj My apologies for the really long delay in getting back you guys. Shame on me, but I didn't document well enough how I managed to replicate this issue. I'll close this out so as to not keep this open without proper replication steps. If I run into this again or manage to replicate it (and document it!) I'll come back.

Thanks for the great work on this package :) Really appreciate it.
