### ISSUE TITLE
WE NEED AUTOMATED TESTS

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#21]
After going through the recent PRs manually, I think we need some unit testing for the library. If anyone has any suggestions for it please comment here.

**Comment by goern** [comment]
Please keep anything you do as pytest wrapped up in setup.py, this way we can run the tests as part of zuul pipelines

**Comment by 4n4nd** [comment]
Added some in #26 we need more for `PrometheusConnect` though

**Comment by 4n4nd** [comment]
Added some more tests for `PrometheusConnect` in #34, but these are not completely automated because you need to specify the url for a prometheus host which has at least 30 minutes of data

**Comment by 4n4nd** [comment]
I will close this issue and continue a similar discussion in #38 since we have added some tests and just need some kind of CI or bot to perform the tests
