### ISSUE TITLE
get_metric_range_data returns empty content

### ISSUE THREAD

**Issue by yrobla** [AICoE/prometheus-api-client-python#222]
When using the get_metric_range_data method, with valid metric and interval, i get empty results.

1. Connect to a prometheus endpoint
2. Set the intervals:

>>> start_time = parse_datetime("100d")
>>> chunk_size=timedelta(days=1)
>>> end_time = parse_datetime("now")

3. Query for data:
metric_data = prom.get_metric_range_data("os_fd_limit", start_time=start_time, end_time=end_time, chunk_size=chunk_size)
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

4. See that the metric is valid and contains data:
end_time = parse_datetime("now")
>>> prom.get_current_metric_value(metric_name='os_fd_limit')
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[{'metric': {'__name__': 'os_fd_limit', 'cluster': 'moc/smaug', 'endpoint': 'etcd-metrics', 'instance': '128.52.62.137:9979', 'job': 'etcd', 'namespace': 'openshift-etcd', 'pod': 'etcd-oct-10-05-control', 'prometheus': 'openshift-monitoring/k8s', 'service': 'etcd'}, 'value': [1635860819.24, '1048576']}, {'metric': {'__name__': 'os_fd_limit', 'cluster': 'moc/smaug', 'endpoint': 'etcd-metrics', 'instance': '128.52.62.187:9979', 'job': 'etcd', 'namespace': 'openshift-etcd', 'pod': 'etcd-oct-10-04-control', 'prometheus': 'openshift-monitoring/k8s', 'service': 'etcd'}, 'value': [1635860819.24, '1048576']}, {'metric': {'__name__': 'os_fd_limit', 'cluster': 'moc/smaug', 'endpoint': 'etcd-metrics', 'instance': '128.52.62.253:9979', 'job': 'etcd', 'namespace': 'openshift-etcd', 'pod': 'etcd-oct-10-06-control', 'prometheus': 'openshift-monitoring/k8s', 'service': 'etcd'}, 'value': [1635860819.24, '1048576']}]

**Comment by 4n4nd** [comment]
Thanks for opening this issue.

I just tested the function with the following code:
```python
prom_url = "https://thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud/"
headers = {"Authorization": "bearer "+my_token}

pc = PrometheusConnect(url=prom_url, headers=headers)

end_time = datetime.datetime.now()
start_time = end_time - datetime.timedelta(hours=1)
data = pc.get_metric_range_data("os_fd_limit", start_time=start_time, end_time=end_time)
```

was able to query it just fine.
