### ISSUE TITLE
`timestamp` index should be DateTimeIndex, not floats

### ISSUE THREAD

**Issue by mmazur** [AICoE/prometheus-api-client-python#231]
The idea behind representing fetched prom data (or any data) as a Pandas DataFrame is to enable the processing of such data with all the powerful Pandas features.

But in case of a timeseries a major component of the data is the actual timestamps, which, to be usable, need to be represented as some form of datetime objects and not unix epoch timestamp floats, as they are now.

I propose to consider whether this shouldn't be changed either by changing the default or at least having all functions give the option of returning the `timestamps` index column converted to DateTimeIndex (similar to how Pandas' `DataFrame.read_csv()` has a `parse_dates` argument).

The code for this might look like this (though maybe there's a faster way):

```
newindex = df.index.to_series().apply(lambda ts: datetime.fromtimestamp(ts))
df.set_index(newindex, inplace=True)
```

**Comment by 4n4nd** [comment]
@chauhankaranraj might be the better person for this issue

**Comment by chauhankaranraj** [comment]
> I propose to consider whether this shouldn't be changed either by changing the default or at least having all functions give the option of returning the `timestamps` index column converted to DateTimeIndex

That sounds liike a good idea, @mmazur! IMO we could change the default behavior to convert the Float64Index to DateTimeIndex when the raw data is being parsed. WDYT?

Also, is this something you'd like to work on? If not, I'm happy to take it up as well :smile:

**Comment by mmazur** [comment]
I'm for changing the default behavior to be more Pandas–like and maybe have an argument `parse_timestamps=True` in the query functions. I've checked and for large enough data sets it does take a while to do the conversion, so there might be cases where people don't care about the timestamps themselves (just need the values) and would like an option of making it go faster by skipping the datetime conversion step.

However, I'm pretty sure I won't have the time to look into it before February, so please feel free. :)

**Comment by chauhankaranraj** [comment]
> there might be cases where people don't care about the timestamps themselves (just need the values) and would like an option of making it go faster by skipping the datetime conversion step.

Yeah that makes sense :+1: 

> However, I'm pretty sure I won't have the time to look into it before February, so please feel free. :)

Sounds good, I'll assign myself to this then :)

/assign chauhankaranraj

**Comment by chauhankaranraj** [comment]
Hey @mmazur, I have added a PR (#234) to change the default dtypes for timestamps in the dataframe classes. Feel free to review it and let us know if you have any feedback!
