### ISSUE TITLE
Add Mock tests for `PrometheusConnect`

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#38]
Add some mock tests for class `PrometheusConnect`, so it can be tested without using a real prometheus instance.

I think we can use the [mock object library](https://docs.python.org/3/library/unittest.mock.html) in python for this

**Comment by anishasthana** [comment]
Would this mock tests be for the purpose of unit testing? Or would it be for an api client user wanting to experiment with the library?

**Comment by 4n4nd** [comment]
Unit testing

**Comment by 4n4nd** [comment]
Oops sorry this should closed
