### ISSUE TITLE
Add store_locally: bool option for get_current_metric_value

### ISSUE THREAD

**Issue by husky-parul** [AICoE/prometheus-api-client-python#69]
Can we have `store_locally: bool` option for `get_current_metric_value` as we have in `get_current_metric_value` ?

**Comment by 4n4nd** [comment]
@goern sesheta don't send me any alerts for this issue on gchat

**Comment by anushkrishnav** [comment]
If it is still open I can work on this

**Comment by anushkrishnav** [comment]
I don't understand why we need to save data through  get_current_metric_value, the work is done through the get_metric_range_data anyway. I would add the option but don't understand why we will need it in both the functions

**Comment by anushkrishnav** [comment]
@4n4nd @goern

**Comment by chauhankaranraj** [comment]
> I don't understand why we need to save data through get_current_metric_value, the work is done through the get_metric_range_data anyway. I would add the option but don't understand why we will need it in both the functions.


Hi Anush, IIUC `get_current_metric_value` and `get_metric_range_data` are geared towards different usecases (former gets values from _current_ timestamp, latter gets values from a _time interval_). So it's possible that a user chooses to use **only one** of these two.

If they're using `get_metric_range_data`, they can save results locally using `store_locally`; but if they're using `get_current_metric_value`, they have no way of saving results. I think that's why we'd need that in both functions. Does that answer your question?

**Comment by chauhankaranraj** [comment]
@4n4nd does #152 already implement the required functionality and deprecate `store_locally` altogether? Or do we still need this parameter?

**Comment by 4n4nd** [comment]
@anushkrishnav @chauhankaranraj Ideally I would like to deprecate `store_locally` and create a new "adapter" that can be used to store data to different types of storages. For example, the same adapter could be used to store data on a file system as well as on other types like S3. This would make it easier for us to add new storage types in the future.

**Comment by anushkrishnav** [comment]
Interesting , I would love to work on it , any existing examples you can share?

**Comment by 4n4nd** [comment]
> Interesting , I would love to work on it , any existing examples you can share?

Yeah I can assign this card to @anushkrishnav but I don't have any examples unfortunately :(

**Comment by anushkrishnav** [comment]
I will get started on it but can you explain it a bit more .

**Comment by 4n4nd** [comment]
@anushkrishnav I was thinking about something like this [object store package they use in thanos](https://github.com/thanos-io/thanos/tree/master/pkg/objstore)

**Comment by anushkrishnav** [comment]
Can I make use of [object-store package](https://pypi.org/project/object-store/)
