### ISSUE TITLE
client exits when chunk size too big instead of raising an exception

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#79]
Here: https://github.com/AICoE/prometheus-api-client-python/blob/15f0185c19dcd1ec9a1d51262db03bae572e705a/prometheus_api_client/prometheus_connect.py#L164

When the chunk size is greater than end_time - start_time, the client just exits printing an error, it should raise an exception instead

**Comment by anushkrishnav** [comment]
I would love to work on this

**Comment by goern** [comment]
@anushkrishnav go ahead, have fun und let us know if you need help! 

/assign @anishasthana 
Cc: @durandom

**Comment by anishasthana** [comment]
/assign @anushkrishnav
assuming we had a slight mistake here with the assignment :-)

**Comment by anushkrishnav** [comment]
> @anushkrishnav go ahead, have fun und let us know if you need help!
> 
> /assign @anishasthana
> Cc: @durandom

Sure

**Comment by anushkrishnav** [comment]
Closing this issue since my PR should fix the issue.
