### ISSUE TITLE
cache results

### ISSUE THREAD

**Issue by durandom** [AICoE/prometheus-api-client-python#82]
ability to cache the results to disk and read from disk.
```
filename = md5(query)
result = client.q(query)
put(result, filename)
```

the problem might be with a `now` in the query.

**Comment by martinpovolny** [comment]
@4n4nd : I'd volunteer to get this done. I am looking for a nice way to do it.

I think that the goal should be that any external calls (to thanos/prometheus) could be cached. 

That means if you would run a notebook such as `MetricsList_example.ipynb` with the caching enables, any query to the server would be executed only the first time even if you re-evaluate the notebook cell with the statement that caused the network communication. That would be useful to speed up work when debugging notebooks and also to lower the load on prometheus/thanos.

And if you distributed the cache content with your notebook you would be able to play your notebook w/o changes w/o talking to a Prometheus server. That would be useful e.g. when you do not want or cannot share access credentials with the audience.

For the needs of anymaly detection I did something similar in a very trivial way here: https://github.com/aicoe-aiops/ocp4-anomaly-detection/blob/master/prom_query.py#L45
My problem was also the reliability of the thanos server at that time.

In https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/prometheus_connect.py#L145 I see you there's `store_locally`.

Is that meant to be used similarly?

Or we could add some caching around each of the `self._session.get(` call. That would be pretty straightforward and would serve the purpose.

WDYT?

**Comment by 4n4nd** [comment]
> @4n4nd : I'd volunteer to get this done. I am looking for a nice way to do it.

Thanks, that would be awesome :+1: 

> Or we could add some caching around each of the self._session.get( call. That would be pretty straightforward and would serve the purpose.

that seems like a great idea to me, but do you think it would be better to just cache jsons instead of pickled dataframes?

**Comment by martinpovolny** [comment]
> that seems like a great idea to me, but do you think it would be better to just cache jsons instead of pickled dataframes?

sure, if we place the caching around `self._session.get(` I'd cache jsons.

I cached pickled dataframes in my case because I placed the caching much higher in abstraction.

Ok, I'll make a PR.
