### ISSUE TITLE
DataFrame representation of all metrics at a given timestamp

### ISSUE THREAD

**Issue by chauhankaranraj** [AICoE/prometheus-api-client-python#86]
Currently, the `MetricList` class can be used to group a metric time series by unique label configs. (See `How MetricsList works` in [MetricList_example.ipynb](https://github.com/AICoE/prometheus-api-client-python/blob/master/examples/MetricsList_example.ipynb)). This lets the user work with a metric by working with time series values in `Metric` objects separately.

However in some use cases you might need to work with values of a metric for all different label configs, at a given timestamp.So we need a easy-to-work-with representation for this task.

The basic difference between what's already in the library and what this issue asks  for is
1) What exists

metric = 
```
badger_disk_writes:rate1m_Fourier {'ae_source': 'https://prometheus-exporter-alpha-0.thoth-dgraph-stage.svc:8080/debug/prometheus_metrics', 'instance': 'prometheus-aggregate-exporter-thoth-dgraph-stage.cloud.paas.psi.redhat.com:80', 'job': 'Thoth Dgraph aggregate-exporter (stage)', 'monitor': 'datahub', 'value_type': 'yhat_lower'} 
```
timeseries =
| timestamp  | value |
| ------------- | ------------- |
| 2020-02-02  | 0  |

metric = 
```
badger_disk_writes:rate1m_Fourier {'ae_source': 'https://prometheus-exporter-alpha-0.thoth-dgraph-stage.svc:8080/debug/prometheus_metrics', 'instance': 'prometheus-aggregate-exporter-thoth-dgraph-stage.cloud.paas.psi.redhat.com:80', 'job': 'Thoth Dgraph aggregate-exporter (stage)', 'monitor': 'datahub', 'value_type': 'yhat_upper'} 
```
timeseries =
| timestamp  | value |
| ------------- | ------------- |
| 2020-02-02  | 1  |

2) What this issue asks for

timestamp = 2020-02-02
| name  | ae_source | value_type | value | timestamp |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| badger_disk_writes:rate1m_Fourier | thesource | yhat_lower | 0 | 1583355394 |
| badger_disk_writes:rate1m_Fourier | thesource | yhat_upper | 1 | 1583355394 |

**Comment by 4n4nd** [comment]
so if I am correct, @chauhankaranraj will implement a new class called `MetricSnapshot` (maybe some other name) that will instead of looking at the data as a time-series, will look at multiple metric values at an instance. i.e. A snapshot of multiple metrics at a given timestamp.
